### ISSUE TITLE
Suggestion ResultValidnessAssertions ContainsMessage(..)

### ISSUE THREAD

**Issue by ROSDEV** [Qowaiv/qowaiv-validation#66]
Add ContainsMessage(IValidationMessage message) in ResultValidnessAssertions

`public static void ContainsMessage(IValidationMessage message)
    {
        Execute.Assertion.ForCondition(Messages.Contains(message))
            .FailWith($"Expected: {message.Message} but could not find it");
            //Might extend result with the actual found messages.            
    }`
Reasoning   
Larger models tend to have a lot of setup with growing validation setting up eveything so we valididate that one message you want to verify becomes very tedious.

**Comment by Corniel** [comment]
I think I understand your request. However, there are some practical issues, all related to naming.

Currently `.WithMessage()`, and `.WithMessages()` both exist, requiring all expected message(s) to be specified. I do not want to change the behaviour of this (would be a breaking change).

In other words: the naming should not be confusing, and working well with the existing two methods.

**Comment by LauraXiulan** [comment]
I would not be in favor of this feature. For me the fact that all the messages have to be specified, guarantees that I don't miss any unexpected messages returned, making it less error prone. If you only want to specify one message, I would expect the model to be setup in such a way that it will only return that specific message because that is the test case that you are running. If the model is so large that the setup will become unmanageable, it might be time to look at the model itself.
